export const Province = [
    { id: "00", label: "กระบี่", value: "กระบี่", symbol: "Krabi" },
    { id: "01",label: "กรุงเทพมหานคร",value: "กรุงเทพมหานคร",symbol: "Bangkok" },
    { id: "02",label: "กาญจนบุรี",value: "กาญจนบุรี",symbol: "Kanchanaburi"},
    { id: "03",label: "กาฬสินธุ์",value: "กาฬสินธุ์",symbol: "Kalasin" },
    { id: "04",label: "กำแพงเพชร",value: "กำแพงเพชร",symbol: "Kamphaeng_Phet" },
    { id: "05", label: "ขอนแก่น", value: "ขอนแก่น", symbol: "Khon_Kaen" },
    { id: "06",label: "จันทบุรี",value: "จันทบุรี",symbol: "Chanthaburi" },
    { id: "07",label: "ฉะเชิงเทรา",value: "ฉะเชิงเทรา",symbol: "Chachoengsao" },
    { id: "08", label: "ชลบุรี", value: "ชลบุรี", symbol: "Chon_Buri" },
    { id: "09", label: "ชัยนาท", value: "ชัยนาท", symbol: "Chai_Nat" },
    { id: "10",label: "ชัยภูมิ",value: "ชัยภูมิ",symbol: "Chaiyaphum" },
    { id: "11", label: "ชุมพร", value: "ชุมพร", symbol: "Chumphon" },
    { id: "12",label: "เชียงราย",value: "เชียงราย",symbol: "Chiang_Rai" },
    { id: "13",label: "เชียงใหม่",value: "เชียงใหม่",symbol: "Chiang_Mai" },
    { id: "14", label: "ตรัง", value: "ตรัง", symbol: "Trang" },
    { id: "15", label: "ตราด", value: "ตราด", symbol: "Trat" },
    { id: "16", label: "ตาก", value: "ตาก", symbol: "Tak" },
    { id: "17",label: "นครนายก",value: "นครนายก",symbol: "Nakhon_Nayok" },
    { id: "18",label: "นครปฐม",value: "นครปฐม",symbol: "Nakhon_Pathom" },
    { id: "19",label: "นครพนม",value: "นครพนม",symbol: "Nakhon_Phanom" },
    { id: "20",label: "นครราชสีมา",value: "นครราชสีมา",symbol: "Nakhon_Ratchasima" },
    { id: "21",label: "นครศรีธรรมราช",value: "นครศรีธรรมราช",symbol: "Nakhon_Si_Thammarat" },
    { id: "22",label: "นครสวรรค์",value: "นครสวรรค์",symbol: "Nakhon_Sawan" },
    { id: "23",label: "นนทบุรี",value: "นนทบุรี",symbol: "Nonthaburi" },
    { id: "24",label: "นราธิวาส",value: "นราธิวาส",symbol: "Narathiwat" },
    { id: "25", label: "น่าน", value: "น่าน", symbol: "Nan" },
    { id: "26", label: "บึงกาฬ", value: "บึงกาฬ", symbol: "Bueng_Kan" },
    { id: "27",label: "บุรีรัมย์",value: "บุรีรัมย์",symbol: "Buri_Ram" },
    { id: "28",label: "ปทุมธานี",value: "ปทุมธานี",symbol: "Pathum_Thani" },
    { id: "29",label: "ประจวบคีรีขันธ์",value: "ประจวบคีรีขันธ์",symbol: "Prachuap_Khiri_Khan" },
    { id: "30",label: "ปราจีนบุรี",value: "ปราจีนบุรี",symbol: "Prachin_Buri" },
    { id: "31", label: "ปัตตานี", value: "ปัตตานี", symbol: "Pattani" },
    { id: "32",label: "พระนครศรีอยุธยา",value: "พระนครศรีอยุธยา",symbol: "Phra_Nakhon_Si_Ayutthaya" },
    { id: "33", label: "พะเยา", value: "พะเยา", symbol: "Phayao" },
    { id: "34", label: "พังงา", value: "พังงา", symbol: "Phangnga" },
    { id: "35", label: "พัทลุง", value: "พัทลุง", symbol: "Phatthalung" },
    { id: "36", label: "พิจิตร", value: "พิจิตร", symbol: "Phichit" },
    { id: "37",label: "พิษณุโลก",value: "พิษณุโลก",symbol: "Phitsanulok" },
    { id: "38",label: "เพชรบุรี",value: "เพชรบุรี",symbol: "Phetchaburi" },
    { id: "39",label: "เพชรบูรณ์",value: "เพชรบูรณ์",symbol: "Phetchabun" },
    { id: "40", label: "แพร่", value: "แพร่", symbol: "Phrae" },
    { id: "41", label: "ภูเก็ต", value: "ภูเก็ต", symbol: "Phuket" },
    { id: "42",label: "มหาสารคาม",value: "มหาสารคาม",symbol: "Maha_Sarakham" },
    { id: "43",label: "มุกดาหาร",value: "มุกดาหาร",symbol: "Mukdahan" },
    { id: "44",label: "แม่ฮ่องสอน",value: "แม่ฮ่องสอน",symbol: "Mae_Hong_Son" },
    { id: "45", label: "ยโสธร", value: "ยโสธร", symbol: "Yasothon" },
    { id: "46", label: "ยะลา", value: "ยะลา", symbol: "Yala" },
    { id: "47", label: "ร้อยเอ็ด", value: "ร้อยเอ็ด", symbol: "Roi_Et" },
    { id: "48", label: "ระนอง", value: "ระนอง", symbol: "Ranong" },
    { id: "49", label: "ระยอง", value: "ระยอง", symbol: "Rayong" },
    { id: "50",label: "ราชบุรี",value: "ราชบุรี",symbol: "Ratchaburi" },
    { id: "51", label: "ลพบุรี", value: "ลพบุรี", symbol: "Lop_Buri" },
    { id: "52", label: "ลำปาง", value: "ลำปาง", symbol: "Lampang" },
    { id: "53", label: "ลำพูน", value: "ลำพูน", symbol: "Lamphun" },
    { id: "54", label: "เลย", value: "เลย", symbol: "Loei" },
    { id: "55",label: "ศรีสะเกษ",value: "ศรีสะเกษ",symbol: "Si_Sa_Ket" },
    { id: "56",label: "สกลนคร",value: "สกลนคร",symbol: "Sakon_Nakhon" },
    { id: "57", label: "สงขลา", value: "สงขลา", symbol: "Songkhla" },
    { id: "58", label: "สตูล", value: "สตูล", symbol: "Satun" },
    { id: "59",label: "สมุทรปราการ",value: "สมุทรปราการ",symbol: "Samut_Prakan" },
    { id: "60",label: "สมุทรสงคราม",value: "สมุทรสงคราม",symbol: "Samut_Songkhram" },
    { id: "61",label: "สมุทรสาคร",value: "สมุทรสาคร",symbol: "Samut_Sakhon" },
    { id: "62", label: "สระแก้ว", value: "สระแก้ว", symbol: "Sa_Kaeo" },
    { id: "63", label: "สระบุรี", value: "สระบุรี", symbol: "Saraburi" },
    { id: "64",label: "สิงห์บุรี",value: "สิงห์บุรี",symbol: "Sing_Buri" },
    { id: "65", label: "สุโขทัย", value: "สุโขทัย", symbol: "Sukhothai" },
    { id: "66",label: "สุพรรณบุรี",value: "สุพรรณบุรี",symbol: "Suphan_Buri" },
    { id: "67",label: "สุราษฎร์ธานี",value: "สุราษฎร์ธานี",symbol: "Surat_Thani" },
    { id: "68", label: "สุรินทร์", value: "สุรินทร์", symbol: "Surin" },
    { id: "69", label: "หนองคาย", value: "หนองคาย", symbol: "Nong_Khai" },
    { id: "70",label: "หนองบัวลำภู",value: "หนองบัวลำภู",symbol: "Nong_Bua_Lam_Phu" },
    { id: "71", label: "อ่างทอง", value: "อ่างทอง", symbol: "Ang_Thong" },
    { id: "72",label: "อำนาจเจริญ",value: "อำนาจเจริญ",symbol: "Amnat_Charoen" },
    { id: "73",label: "อุดรธานี",value: "อุดรธานี",symbol: "Udon_Thani" },
    { id: "74",label: "อุตรดิตถ์",value: "อุตรดิตถ์",symbol: "Uttaradit" },
    { id: "75",label: "อุทัยธานี",value: "อุทัยธานี",symbol: "Uthai_Thani" },
    { id: "76",label: "อุบลราชธานี",value: "อุบลราชธานี",symbol: "Ubon_Ratchathani" }
]